keys:
  - &host_organ age1rz56p7reneqrucw0ypm34jqjkc85ulqpgevpcakna0slez880y9sm2ujem
  - &host_harmonium age143ct57jy20uqp9pdayn7z09axq9me40vlw8uaf3dm8myh6kkw94s36y3zf
  - &jakub_lur age1ryedalt0ajly0l03sr7tfmuv7fvqcuaeq889try48zz0v7usnaeqskt5xd
  - &jakub_harmonium age1kltklwj0f483lu0r3tn3ujpyangym430wg0cd76zn62lf7xhl5cswqugrq
  - &jakub_nyckelharpa age1nk3l83s0k98sv3gvsm20f0ssdpk45hs8zkxajtw3e20fu263fcjqwvjs7u

creation_rules:
  - path_regex: hosts/organ/secrets.yaml$
    key_groups:
    - age:
      - *host_organ
      - *jakub_harmonium
      - *jakub_lur
      - *jakub_nyckelharpa
  - path_regex: hosts/harmonium/secrets.yaml$
    key_groups:
    - age:
      - *host_harmonium
      - *jakub_harmonium
      - *jakub_lur
      - *jakub_nyckelharpa

