keys:
  - &admin_jakub age1mweq7c3fq28ezr28fvhkula3fhhyzq0hpmyjgzsvvhh2vr5y33psr9hv83
  - &server_organ age1rz56p7reneqrucw0ypm34jqjkc85ulqpgevpcakna0slez880y9sm2ujem

creation_rules:
  - path_regex: hosts/organ/secrets.yaml$
    key_groups:
    - age:
      - *admin_jakub
      - *server_organ

