{
  config,
  lib,
  ...
}: {
  nix.enable = false; # Required for use with Determinate Nix
  environment.etc."nix/nix.custom.conf".text = ''
    # This custom configuration file for Determinate Nix is generated by the determinate module for nix-darwin.
    # Update your custom settings by changing your nix-darwin configuration, not by modifying this file directly.

    trusted-users = root ${config.username}
    warn-dirty = false
    use-xdg-base-directories = true
  '';

  # Fix to use XDG based profile
  environment.profiles = lib.mkForce [
    "$HOME/.local/state/nix/profile"
    "/run/current-system/sw"
    "/nix/var/nix/profiles/default"
  ];
}
