# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0b526783-7d0a-472c-be45-b698c91d5e4e";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.reusePassphrases = true;
  boot.initrd.luks.devices."funkhaus" = {
    allowDiscards = true;
    device = "/dev/disk/by-uuid/4788c5c6-93fe-4b69-aff0-6ef167134a55";
  };
  boot.initrd.luks.devices."vynilrecord" = {
    allowDiscards = true;
    device = "/dev/disk/by-uuid/421bf996-324b-4264-91a0-7845e4e3bef5";
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0b526783-7d0a-472c-be45-b698c91d5e4e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0b526783-7d0a-472c-be45-b698c91d5e4e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/0b526783-7d0a-472c-be45-b698c91d5e4e";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/0b526783-7d0a-472c-be45-b698c91d5e4e";
      fsType = "btrfs";
      options = [ "subvol=log" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/27A8-9AFE";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ab0c599-aac1-44f9-aac3-b0405c8dcd83"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
