# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/22364278-ec92-4364-9c96-f68059323d71";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.reusePassphrases = true;
  boot.initrd.luks.devices."funkhaus" = {
    allowDiscards = true;
    device = "/dev/disk/by-uuid/3205b7d8-9293-4c5d-87b7-1ce14f52dd8e";
  };
  boot.initrd.luks.devices."vynilrecord" = {
    allowDiscards = true;
    device = "/dev/disk/by-uuid/062dbab4-cb6f-4866-a6f9-e775270aa99d";
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/22364278-ec92-4364-9c96-f68059323d71";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/22364278-ec92-4364-9c96-f68059323d71";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/22364278-ec92-4364-9c96-f68059323d71";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/22364278-ec92-4364-9c96-f68059323d71";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/27A8-9AFE";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/906ed498-51ee-467b-a4da-bfdf884d756c"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
