$ORIGIN	jakubarbet.me.
$TTL	1h

@	IN	SOA	ns2.he.net. root.jakubarbet.me. (
                          2023022001	;serial
                          3600		;refresh [1h]
                          600		;retry   [10m]
                          1209600	;expire  [14d]
                          3600  ) 	;min TTL [1h]

@	IN	NS	ns2.he.net.
@	IN	NS	ns3.he.net.
@	IN	NS	ns4.he.net.
@	IN	NS	ns5.he.net.

@           	IN	A	3.72.221.227
@           	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
www          	IN	A	3.72.221.227
www          	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
mail        	IN	A	3.72.221.227
mail        	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
autoconfig  	IN	A	3.72.221.227
autoconfig  	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
autodiscover	IN	A	3.72.221.227
autodiscover	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
drive       	IN	A	3.72.221.227
drive       	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
calendar     	IN	A	3.72.221.227
calendar     	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
git         	IN	A	3.72.221.227
git         	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19
analyser    	IN	A	3.72.221.227
analyser    	IN	AAAA	2a05:d014:5e7:c201:a52:7a92:2383:dc19

@	IN	CAA	0 iodef mailto:root@jakubarbet.me
@	IN	CAA	0 issue letsencrypt.org

@	IN	MX	10 organ.jakubarbet.me.
@	IN	TXT	"v=spf1 ip4:3.72.221.227 include:amazonses.com ~all"
_dmarc  IN	TXT	"v=DMARC1; p=quarantine; pct=100; adkim=s; aspf=s;"

mail	IN	MX	10 feedback-smtp.eu-central-1.amazonses.com.
mail	IN	TXT	"v=spf1 include:amazonses.com ~all"

imap  IN  CNAME jakubarbet.me.
smtp  IN  CNAME jakubarbet.me.
@ IN  TXT "mailconf=https://autoconfig.jakubarbet.me/mail/config-v1.1.xml"

_imaps._tcp         IN  SRV 0 0 993 mail.jakubarbet.me.
_submission._tcp    IN  SRV 0 0 587 mail.jakubarbet.me.
_autodiscover._tcp  IN  SRV 0 0 443 autodiscover.jakubarbet.me.

@	IN	SSHFP	1 1 9e037c63ca8d6f8a3063a2d7ec1c348d9fd7f0eb
@	IN	SSHFP	1 2 0109753da7ea00ebe715e1ddb43f6b15bc9f1b33c048e185886e4e5843d6bc53
@	IN	SSHFP	4 1 a0152a309ae28b44cb9839c3ab6340c6c030ac3f
@	IN	SSHFP	4 2 c843f168faa273c4ff83b9c211e971919f02de3f6ecd69b9c6ee17edb2564512

